### PR TITLE
Lts 9.20

### PR DESCRIPTION
**Pull request by dfithian**
I took the base Haskell image as it was from the other repository I found. Here's the image with which I was able to successfully build our shared code.

Dockerhub repo, building automatically:
https://hub.docker.com/r/tvisioninsights/circleci-docker-haskell/

Let me know what you think about my naming scheme on the Build Settings tab.

### CODE REVIEW

**Comment by ystael** [comment]
It seems to me that the standard convention is to use unqualified release numbers as version tags for Docker images, so an idiomatic version tag for us (assuming there is no other significant version number) would be simply `lts-9.20` rather than `release-lts-9.20`.

**Comment by dfithian** [comment]
Okay. I can get rid of the branch building and just do tags so they don't conflict

**Comment by dfithian** [comment]
Otherwise maybe let's agree to prefix branch builds with dev-

**Comment by dfithian** [comment]
Alright I switched up the naming schemes. Happy to iterate on it.

**Pull request merged**
